services:
  postgres:
    container_name: animal-postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: animal-admin
      POSTGRES_PASSWORD: animal-admin
      POSTGRES_DB: animal-admin
    ports:
      - "5557:5432"
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U animal-admin"]
      interval: 5s
      timeout: 5s
      retries: 5
